# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TerrainDerivatives
                                 A QGIS plugin
 Produces terrain derivatives from a DEM
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-08-31
        copyright            : (C) 2021 by Divan
        email                : vermeulendivan@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Divan'
__date__ = '2021-08-31'
__copyright__ = '(C) 2021 by Divan'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TerrainDerivatives class from file TerrainDerivatives.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .terrain_derivatives import TerrainDerivativesPlugin
    return TerrainDerivativesPlugin()
